DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS userdata;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE userdata (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	operator_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	FOREIGN KEY (operator_id) REFERENCES user (id)
);